const data={props:[['Oakstone Rental A','Rental','Occupied','$2,300'],['Pinecrest Rental B','Rental','Vacant','$1,950'],['Sample Ridge Flip','Flip','Rehab','—']],projects:[['Oakstone Kitchen Refresh','In Progress','Oakstone Rental A','$12,000'],['Sample Ridge Rehab','Planning','Sample Ridge Flip','$42,000']],contacts:[['Demo Contact A','Tenant','555-0101'],['Demo Supply Co.','Vendor','555-0102'],['Sample Contractor Group','Contractor','555-0103']],tx:[['Demo rent payment','Income','Rental Income','+$2,300'],['Demo materials purchase','Expense','Materials','-$875'],['Demo labor payment','Expense','Labor','-$1,800']],audit:[]};
let role='owner',page='dash';const labels={owner:'Owner/Admin',manager:'Project Manager',accountant:'Accountant',viewer:'Viewer'};const perms={owner:['all'],manager:['dash','props','projects','contacts','security'],accountant:['dash','tx','reports','security'],viewer:['dash','reports']};const can=p=>perms[role].includes('all')||perms[role].includes(p);const $=id=>document.getElementById(id);
function login(){if($('pass').value!=='demo123')return alert('Password demo incorrecto');role=$('role').value;$('login').style.display='none';data.audit.unshift([new Date().toLocaleString(),labels[role],'login']);render()}
function logout(){$('login').style.display='grid';$('app').innerHTML=''}
function menu(x){const s=document.querySelector('.side');if(s)s.classList.toggle('open',x);$('cover').classList.toggle('on',x)}
function go(p){if(!can(p))return alert('Tu rol no tiene acceso en este demo');page=p;menu(false);render()}
function del(kind,name){let pin=prompt('PIN demo para borrar');if(pin!=='2468')return alert('PIN incorrecto');if(confirm('¿Borrar '+name+'?')){data.audit.unshift([new Date().toLocaleString(),labels[role],'delete '+kind]);alert('Borrado demo registrado')}}
function nav(){return [['dash','📊 Dashboard'],['props','🏠 Properties'],['projects','🔨 Projects'],['contacts','👥 Contacts'],['tx','💵 Transactions'],['reports','📈 Reports'],['security','🛡️ Security'],['audit','📋 Audit']].map(n=>`<button class="${page==n[0]?'on':''} ${can(n[0])?'':'lock'}" onclick="go('${n[0]}')">${n[1]}</button>`).join('')}
function row(a,kind='item'){return `<div class="row"><div><b>${a[0]}</b><span>${a.slice(1,-1).join(' · ')}</span></div><div><span class="badge">${a[a.length-1]}</span> ${role==='owner'?`<button class="danger" onclick="del('${kind}','${a[0]}')">Delete</button>`:''}</div></div>`}
function list(arr,k){return arr.map(x=>row(x,k)).join('')}
function stat(l,v,c=''){return `<div class="card"><div class="label">${l}</div><div class="value ${c}">${v}</div></div>`}
function shell(content){$('app').innerHTML=`<div class="layout"><aside class="side"><div class="logo">NJ</div><h2>N&J</h2><small>${labels[role]}</small><nav class="nav">${nav()}</nav></aside><main class="main"><div class="top"><button class="hamb" onclick="menu(true)">☰</button><b>N&J Command Center</b><button onclick="logout()">Salir</button></div>${content}</main></div>`}
function render(){let c='';if(page==='dash')c=`<div class="card"><div class="label">V5.4 Restore</div><h1>Dashboard inteligente</h1><p>Datos falsos, login demo y módulos principales restaurados.</p></div><div class="grid g4">${stat('Income','$2,300','green')}${stat('Expenses','$2,675','red')}${stat('Net','-$375','red')}${stat('Role',role,'blue')}</div><div class="grid g2"><div class="card"><h3>Properties</h3>${list(data.props,'property')}</div><div class="card"><h3>Projects</h3>${list(data.projects,'project')}</div></div>`;if(page==='props')c=`<div class="card"><h1>Properties</h1>${list(data.props,'property')}</div>`;if(page==='projects')c=`<div class="card"><h1>Projects</h1>${list(data.projects,'project')}</div>`;if(page==='contacts')c=`<div class="card"><h1>Contacts</h1>${list(data.contacts,'contact')}</div>`;if(page==='tx')c=`<div class="card"><h1>Transactions</h1>${list(data.tx,'transaction')}</div>`;if(page==='reports')c=`<div class="grid g4">${stat('Income','$2,300','green')}${stat('Expenses','$2,675','red')}${stat('Net','-$375','red')}${stat('Records','7')}</div>`;if(page==='security')c=`<div class="card"><h1>Security demo</h1><p class="note">Esto simula login, roles y PIN. La seguridad real será V6 con backend.</p></div>`;if(page==='audit')c=`<div class="card"><h1>Audit</h1>${data.audit.map(a=>row(a,'audit')).join('')}</div>`;shell(c)}