const KEY='nj_command_center_v55';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(+n||0);
const today=new Date().toISOString().slice(0,10);
const labels={tenant:'Inquilino',client:'Cliente',vendor:'Vendor',investor:'Inversionista',team:'Equipo',rental:'Rental',flip:'Flip',lead:'Lead',maintenance:'Mantenimiento',remodeling:'Remodeling',repair:'Repair',admin:'Admin',planned:'Planeado',active:'Activo',waiting:'En espera',inspection:'Inspección',completed:'Terminado',income:'Ingreso',expense:'Gasto',available:'Disponible','under-work':'En trabajo',sold:'Vendida'};
let state=load();
function id(){return'NJ'+Math.random().toString(36).slice(2,8)+Date.now().toString(36).slice(-4)}
function seed(){const c1=id(),c2=id(),p1=id(),p2=id(),p3=id(),j1=id(),j2=id();return{contacts:[{id:c1,type:'tenant',name:'Tenant de prueba',phone:'(502) 000-0000',email:'tenant@example.com',status:'active',linkedPropertyId:p1,notes:'Dato falso'},{id:c2,type:'vendor',name:'Contratista demo',phone:'(502) 111-1111',email:'vendor@example.com',status:'active',trade:'Drywall/Paint'}],properties:[{id:p1,type:'rental',address:'Elmhurst demo',city:'Louisville',state:'KY',contactId:c1,status:'active',monthlyRent:2300,rentDueDay:5,notes:'Rental de ejemplo'},{id:p2,type:'rental',address:'Jessamine demo',city:'Louisville',state:'KY',contactId:'',status:'available',monthlyRent:2100,rentDueDay:5},{id:p3,type:'flip',address:'Flip lead demo',city:'Louisville',state:'KY',contactId:'',status:'lead',purchasePrice:135000,arv:225000,rehabBudget:42000}],projects:[{id:j1,name:'Kitchen opening demo',type:'remodeling',stage:'active',propertyId:p1,contactId:'',budget:8500,spent:3200,notes:'Ejemplo de remodelación'},{id:j2,name:'Bathroom repair demo',type:'repair',stage:'waiting',propertyId:p2,contactId:c2,budget:2600,spent:700}],tx:[{id:id(),kind:'income',date:today,amount:2300,category:'Rent',propertyId:p1,projectId:'',description:'Renta prueba Elmhurst'},{id:id(),kind:'expense',date:today,amount:487,category:'Materials',propertyId:p1,projectId:j1,description:'Home Depot prueba'}]}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch{return seed()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function badge(v){let c=['active','completed'].includes(v)?'green':['waiting','lead'].includes(v)?'yellow':['inspection','under-work'].includes(v)?'purple':'blue';return`<span class="badge ${c}">${esc(labels[v]||v||'—')}</span>`}
function by(a,id){return state[a].find(x=>x.id===id)||{}}
function sum(kind,fn=()=>true){return state.tx.filter(t=>(!kind||t.kind===kind)&&fn(t)).reduce((s,t)=>s+(+t.amount||0),0)}
function fill(){const fillOne=(sel,arr,label)=>{$$(sel).forEach(s=>{let cur=s.value,first=s.querySelector('option[value=""]')?.outerHTML||'<option value="">Sin vínculo</option>';s.innerHTML=first+state[arr].map(x=>`<option value="${x.id}">${esc(label(x))}</option>`).join('');s.value=cur})};fillOne('[data-fill="contacts"]','contacts',x=>x.name);fillOne('[data-fill="properties"]','properties',x=>x.address);fillOne('[data-fill="projects"]','projects',x=>x.name)}
function stat(t,v,s){return`<div class="stat"><small>${t}</small><b>${v}</b><small class="muted">${s}</small></div>`}
function render(){fill();let inc=sum('income'),exp=sum('expense');$('#stats').innerHTML=stat('Propiedades',state.properties.length,`${state.properties.filter(p=>p.type==='rental').length} rentals`)+stat('Proyectos activos',state.projects.filter(p=>p.stage==='active').length,`${state.projects.length} total`)+stat('Ingresos',usd(inc),'registrados')+stat('Net',usd(inc-exp),`${usd(exp)} gastos`);$('#financeStats').innerHTML=stat('Ingresos',usd(inc),'Total')+stat('Gastos',usd(exp),'Total')+stat('Net',usd(inc-exp),'Estimado')+stat('Transacciones',state.tx.length,'Registros');renderDash();renderContacts();renderProps();renderProjects();renderTx()}
function table(head,rows){return`<thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="9" class="muted">No hay datos.</td></tr>'}</tbody>`}
function renderDash(){let r=state.properties.map(p=>{let net=sum('income',t=>t.propertyId===p.id)-sum('expense',t=>t.propertyId===p.id),c=by('contacts',p.contactId);return`<tr><td><b>${esc(p.address)}</b><div class="muted">${esc(p.city)}, ${esc(p.state)}</div></td><td>${badge(p.type)} ${badge(p.status)}</td><td>${esc(c.name||'Sin vínculo')}</td><td><b>${usd(net)}</b></td></tr>`}).join('');$('#dashProps').innerHTML=table(['Propiedad','Tipo/estado','Contacto','Net'],r);$('#stageSummary').innerHTML=['planned','active','waiting','inspection','completed'].map(st=>`<div class="item"><b>${labels[st]}</b><br><span class="muted">${state.projects.filter(p=>p.stage===st).length} proyecto(s)</span></div>`).join('');let centers=[...state.properties.map(p=>({k:'Propiedad',n:p.address,i:sum('income',t=>t.propertyId===p.id),e:sum('expense',t=>t.propertyId===p.id)})),...state.projects.map(p=>({k:'Proyecto',n:p.name,i:sum('income',t=>t.projectId===p.id),e:sum('expense',t=>t.projectId===p.id)}))];$('#costCenters').innerHTML=table(['Centro','Ingresos','Gastos','Net'],centers.map(c=>`<tr><td>${esc(c.n)}<div class="muted">${c.k}</div></td><td>${usd(c.i)}</td><td>${usd(c.e)}</td><td><b>${usd(c.i-c.e)}</b></td></tr>`).join(''))}
function actions(a,id,n){return`<div class="row-actions"><button class="btn" onclick="edit('${a}','${id}')">Editar</button><button class="btn danger" onclick="del('${a}','${id}','${esc(n)}')">Borrar</button></div>`}
function renderContacts(){let r=state.contacts.map(c=>`<tr><td><b>${esc(c.name)}</b><div class="muted">${esc(c.phone||'')}</div></td><td>${badge(c.type)} ${badge(c.status)}</td><td>${esc(c.email||'—')}</td><td>${esc(by('properties',c.linkedPropertyId).address||'Sin vínculo')}</td><td>${actions('contacts',c.id,c.name)}</td></tr>`).join('');$('#contactsTable').innerHTML=table(['Contacto','Tipo/estado','Email','Propiedad',''],r)}
function renderProps(){let r=state.properties.map(p=>`<tr><td><b>${esc(p.address)}</b><div class="muted">${esc(p.city)}, ${esc(p.state)}</div></td><td>${badge(p.type)} ${badge(p.status)}</td><td>${esc(by('contacts',p.contactId).name||'Sin contacto')}</td><td>${p.type==='rental'?usd(p.monthlyRent)+'/mes':p.arv?'ARV '+usd(p.arv):'—'}</td><td>${actions('properties',p.id,p.address)}</td></tr>`).join('');$('#propertiesTable').innerHTML=table(['Propiedad','Tipo/estado','Contacto','Renta/ARV',''],r)}
function renderProjects(){let stages=['planned','active','waiting','inspection','completed'];$('#board').innerHTML=stages.map(st=>`<div class="col"><b>${labels[st]}</b>${state.projects.filter(p=>p.stage===st).map(p=>`<div class="item"><b>${esc(p.name)}</b><div class="muted">${labels[p.type]} • ${usd(p.spent)} / ${usd(p.budget)}</div></div>`).join('')||'<p class="muted">Vacío</p>'}</div>`).join('');let r=state.projects.map(p=>`<tr><td><b>${esc(p.name)}</b><div class="muted">${esc(by('properties',p.propertyId).address||'Sin propiedad')}</div></td><td>${badge(p.type)} ${badge(p.stage)}</td><td>${usd(p.spent)} / ${usd(p.budget)}</td><td>${actions('projects',p.id,p.name)}</td></tr>`).join('');$('#projectsTable').innerHTML=table(['Proyecto','Tipo/etapa','Gastado/presupuesto',''],r)}
function renderTx(){let r=state.tx.map(t=>`<tr><td>${esc(t.date)}<div class="muted">${esc(t.description||'')}</div></td><td>${badge(t.kind)} ${esc(t.category)}</td><td>${esc(by('properties',t.propertyId).address||'—')}</td><td>${esc(by('projects',t.projectId).name||'—')}</td><td><b>${t.kind==='expense'?'-':''}${usd(t.amount)}</b></td><td>${actions('tx',t.id,t.description||t.category)}</td></tr>`).join('');$('#txTable').innerHTML=table(['Fecha','Tipo','Propiedad','Proyecto','Monto',''],r)}
function obj(form){let o=Object.fromEntries(new FormData(form).entries());['monthlyRent','rentDueDay','purchasePrice','arv','rehabBudget','budget','spent','amount','capital'].forEach(k=>{if(k in o)o[k]=o[k]===''?'':+o[k]});return o}
function up(arr,o){if(o.id){let i=state[arr].findIndex(x=>x.id===o.id);state[arr][i]={...state[arr][i],...o}}else{o.id=id();state[arr].push(o)}save()}
function wire(form,arr){let f=$(form);f.addEventListener('submit',e=>{e.preventDefault();up(arr,obj(f));f.reset();f.id.value='';if(f.date)f.date.value=today;smart(f)});f.addEventListener('change',()=>smart(f));f.addEventListener('reset',()=>setTimeout(()=>smart(f)));smart(f)}
function smart(f){if(!f.type)return;let t=f.type.value;f.querySelectorAll('.smart').forEach(x=>x.classList.remove('show'));f.querySelectorAll(`.contact-${t},.property-${t}`).forEach(x=>x.classList.add('show'))}
function edit(arr,idv){let map={contacts:'#contactForm',properties:'#propertyForm',projects:'#projectForm',tx:'#txForm'},f=$(map[arr]),r=state[arr].find(x=>x.id===idv);Object.keys(r).forEach(k=>{if(f[k])f[k].value=r[k]??''});smart(f);show(arr==='tx'?'finance':arr);f.scrollIntoView({behavior:'smooth',block:'center'})}
function del(arr,idv,name){if(!confirm(`¿Estás seguro que quieres borrar "${name}"?\n\nMás adelante esta opción podrá pedir contraseña.`))return;state[arr]=state[arr].filter(x=>x.id!==idv);if(arr==='contacts'){state.properties.forEach(p=>{if(p.contactId===idv)p.contactId=''});state.projects.forEach(p=>{if(p.contactId===idv)p.contactId=''})}if(arr==='properties'){state.contacts.forEach(c=>{if(c.linkedPropertyId===idv)c.linkedPropertyId=''});state.projects.forEach(p=>{if(p.propertyId===idv)p.propertyId=''});state.tx.forEach(t=>{if(t.propertyId===idv)t.propertyId=''})}if(arr==='projects')state.tx.forEach(t=>{if(t.projectId===idv)t.projectId=''});save()}
function show(p){$$('.page').forEach(x=>x.classList.toggle('active',x.id===p));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));let copy={dashboard:['Dashboard inteligente','N&J Command Center','La página principal se alimenta de contactos, propiedades, proyectos y transacciones.'],contacts:['Contactos','Contactos inteligentes','Campos cambian según el tipo de contacto.'],properties:['Propiedades','Propiedades y rentals','Relaciones opcionales con contactos, proyectos y finanzas.'],projects:['Proyectos','Proyectos por etapas','Clasifica remodelaciones, repairs, flips y mantenimiento.'],finance:['Finanzas','P&L por centro de costo','Ingresos y gastos vinculados a propiedades o proyectos.'],settings:['Datos y seguridad','Configuración local','Exporta, importa o resetea datos de prueba.']}[p];$('#kicker').textContent=copy[0];$('#title').textContent=copy[1];$('#lead').textContent=copy[2]}
$$('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));wire('#contactForm','contacts');wire('#propertyForm','properties');wire('#projectForm','projects');wire('#txForm','tx');$('#txForm').date.value=today;$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='nj-command-center-backup.json';a.click()};$('#resetBtn').onclick=()=>{if(confirm('¿Seguro que quieres borrar todos los datos locales y volver a datos de prueba?')){state=seed();save()}};$('#importBtn').onclick=()=>{try{state={contacts:[],properties:[],projects:[],tx:[],...JSON.parse($('#importBox').value)};save();$('#importBox').value=''}catch{alert('JSON inválido')}};render();
